"""Pages 3-4 - fundamentals and the AI / RPO conversion framework."""
from __future__ import annotations

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from . import theme as T
from .theme import Chart


def _src(b):
    return b.sources["fundamentals"] + "; Yahoo Finance (EPS surprise)"


def _labels(q):
    return q["label"].tolist()


def build(b) -> list[Chart]:
    out: list[Chart] = []
    q = b.q[b.q.index >= "2014-06-01"]
    qq = q.copy()
    lbl = _labels(qq)
    src = _src(b)
    rng = f"{q['label'].iloc[0]} to {q['label'].iloc[-1]} (quarters ended {q.index[0].date()} - {q.index[-1].date()})"

    # ---- P3.1 revenue + growth
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, row_heights=[0.6, 0.4], vertical_spacing=0.07)
    fig.add_trace(go.Bar(x=lbl, y=qq["revenue"] / 1e3, name="Revenue ($bn)", marker_color=T.BLUE), 1, 1)
    fig.add_trace(go.Scatter(x=lbl, y=qq["revenue_yoy"], name="Revenue growth YoY", line=dict(color=T.ORANGE, width=2.2)), 2, 1)
    fig.add_hline(y=0, line=dict(color=T.AXIS, width=1), row=2, col=1)
    T.style(fig, "Quarterly revenue and year-on-year growth", None, None, height=470)
    fig.update_yaxes(title_text="Revenue (USD bn)", row=1, col=1)
    fig.update_yaxes(title_text="YoY growth", tickformat=".0%", row=2, col=1)
    fig.update_xaxes(title_text="Fiscal quarter (FYE May)", row=2, col=1, tickangle=-60, nticks=16)
    out.append(Chart("rev_growth", 3, fig, "Quarterly revenue and year-on-year growth",
                     f"Total revenue by fiscal quarter and its growth against the same quarter a year earlier (seasonality, e.g. a strong fiscal Q4, is why growth is measured YoY). "
                     f"Median YoY growth over the window is {qq['revenue_yoy'].median():.1%}; the latest quarter ({qq['label'].iloc[-1]}) grew {qq['revenue_yoy'].iloc[-1]:.1%}, "
                     f"against a peak of {qq['revenue_yoy'].max():.1%} ({qq['label'][qq['revenue_yoy'].idxmax()]}).", src, rng))

    # ---- P3.2 margins
    fig = go.Figure()
    for col, name, color in (("gross_margin_proxy", "Gross margin (proxy)", T.AQUA), ("ebitda_margin", "EBITDA margin (quarter)", T.VIOLET),
                             ("operating_margin", "GAAP operating margin (quarter)", T.BLUE), ("fcf_margin_ttm", "FCF margin (TTM)", T.ORANGE)):
        fig.add_trace(go.Scatter(x=lbl, y=qq[col], name=name, line=dict(color=color, width=2.2)))
    fig.add_hline(y=0, line=dict(color=T.AXIS, width=1))
    T.style(fig, "Margin structure: gross, EBITDA, operating and free-cash-flow margins", "Fiscal quarter (FYE May)", "% of revenue", height=430, y_tickformat=".0%")
    fig.update_xaxes(tickangle=-60, nticks=16)
    out.append(Chart("margins", 3, fig, "Margin structure: gross, EBITDA, operating and free-cash-flow margins",
                     "Profitability at four levels. Oracle does not report gross profit, so the gross-margin proxy is revenue less the cloud/licence-support, hardware and services cost lines. "
                     f"Latest quarter: gross-margin proxy {qq['gross_margin_proxy'].iloc[-1]:.1%} (vs {qq['gross_margin_proxy'].iloc[-9]:.1%} two years earlier), GAAP operating margin "
                     f"{qq['operating_margin'].iloc[-1]:.1%}, TTM FCF margin {qq['fcf_margin_ttm'].iloc[-1]:.1%}. Capital spending hits free cash flow immediately but reaches operating margin "
                     "only gradually through depreciation - so the two can diverge for years.", src, rng))

    # ---- P3.3 OCF vs capex vs FCF
    fig = go.Figure()
    fig.add_trace(go.Bar(x=lbl, y=qq["ocf"] / 1e3, name="Operating cash flow", marker_color=T.BLUE))
    fig.add_trace(go.Bar(x=lbl, y=-qq["capex"] / 1e3, name="Capital expenditure (outflow)", marker_color=T.ORANGE))
    fig.add_trace(go.Scatter(x=lbl, y=qq["fcf"] / 1e3, name="Free cash flow (quarter)", line=dict(color=T.INK, width=2.4)))
    T.style(fig, "Operating cash flow, capital expenditure and free cash flow", "Fiscal quarter (FYE May)", "USD bn per quarter", height=450, hover="x")
    fig.update_layout(barmode="relative")
    fig.update_xaxes(tickangle=-60, nticks=16)
    out.append(Chart("cashflow_capex", 3, fig, "Operating cash flow, capital expenditure and free cash flow",
                     f"Cash generated by the business (blue, up) against cash spent on property and equipment (orange, down); the black line is the difference. In {int((qq['capex'] > qq['ocf']).tail(8).sum())} of the "
                     f"last 8 quarters capex exceeded operating cash flow - the central tension of the AI build-out. Capex is cash purchases of PP&E (it excludes finance leases).",
                     src, rng))

    # ---- P3.4 leverage
    fig = make_subplots(rows=3, cols=1, shared_xaxes=True, row_heights=[0.4, 0.3, 0.3], vertical_spacing=0.07,
                        subplot_titles=("Debt, cash and net debt (USD bn)", "Net debt / EBITDA (TTM, x)", "Interest coverage: operating income / interest expense (TTM, x)"))
    fig.add_trace(go.Bar(x=lbl, y=qq["total_debt_incl_leases"] / 1e3, name="Debt incl. finance leases", marker_color=T.AXIS), 1, 1)
    fig.add_trace(go.Scatter(x=lbl, y=qq["net_debt_incl_leases"] / 1e3, name="Net debt", line=dict(color=T.BLUE, width=2.4)), 1, 1)
    fig.add_trace(go.Scatter(x=lbl, y=qq["cash_and_securities"] / 1e3, name="Cash & securities", line=dict(color=T.AQUA, width=2)), 1, 1)
    fig.add_trace(go.Scatter(x=lbl, y=qq["net_debt_to_ebitda_ttm"], name="Net debt / EBITDA", line=dict(color=T.ORANGE, width=2.2)), 2, 1)
    fig.add_trace(go.Scatter(x=lbl, y=qq["interest_coverage_ttm"], name="Interest coverage", line=dict(color=T.VIOLET, width=2.2)), 3, 1)
    T.style(fig, "Balance-sheet risk: leverage and coverage", None, None, height=640)
    fig.update_xaxes(title_text="Fiscal quarter (FYE May)", tickangle=-60, nticks=16, row=3, col=1)
    out.append(Chart("leverage", 3, fig, "Balance-sheet risk: leverage and coverage",
                     f"Net debt (incl. finance leases) is ${qq['net_debt_incl_leases'].iloc[-1]/1e3:,.0f}bn vs ${qq['net_debt_incl_leases'].iloc[-9]/1e3:,.0f}bn two years earlier; net debt/EBITDA is "
                     f"{qq['net_debt_to_ebitda_ttm'].iloc[-1]:.1f}x and interest cover {qq['interest_coverage_ttm'].iloc[-1]:.1f}x. Ratios can look stable while absolute debt climbs because EBITDA is also growing "
                     "- watch both. Operating-lease obligations are not included in debt here.",
                     src, rng))

    # ---- P3.5 EPS and shares
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, row_heights=[0.6, 0.4], vertical_spacing=0.07)
    fig.add_trace(go.Bar(x=lbl, y=qq["eps_diluted"], name="GAAP diluted EPS (quarter)", marker_color=T.BLUE), 1, 1)
    fig.add_trace(go.Scatter(x=lbl, y=qq["eps_nongaap_actual"], name="Non-GAAP EPS (Yahoo)", line=dict(color=T.ORANGE, width=2.2)), 1, 1)
    fig.add_trace(go.Scatter(x=lbl, y=qq["diluted_shares"], name="Diluted shares (m)", line=dict(color=T.VIOLET, width=2.2)), 2, 1)
    T.style(fig, "Earnings per share and share count", None, None, height=470, hover="x")
    fig.update_yaxes(title_text="EPS (USD)", row=1, col=1)
    fig.update_yaxes(title_text="Diluted shares (m)", row=2, col=1)
    fig.update_xaxes(title_text="Fiscal quarter (FYE May)", tickangle=-60, nticks=16, row=2, col=1)
    out.append(Chart("eps_shares", 3, fig, "Earnings per share and share count",
                     f"GAAP EPS (bars) against the non-GAAP figure analysts forecast (line; it excludes items such as stock compensation and amortisation). Diluted shares moved from "
                     f"{qq['diluted_shares'].iloc[-21]:,.0f}m to {qq['diluted_shares'].iloc[-1]:,.0f}m over the last five years; a rising count after years of buybacks signals equity "
                     "issuance to part-fund the build-out.", src, rng))

    # ---- P3.6 capital intensity
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=lbl, y=qq["capex_to_ocf_ttm"], name="Capex / operating cash flow (TTM)", line=dict(color=T.ORANGE, width=2.4)))
    fig.add_trace(go.Scatter(x=lbl, y=qq["capex_to_revenue_ttm"], name="Capex / revenue (TTM)", line=dict(color=T.BLUE, width=2.4)))
    fig.add_hline(y=1.0, line=dict(color=T.RED, width=1, dash="dot"), annotation_text="capex = 100%", annotation_position="top left")
    T.style(fig, "Capital intensity: capex relative to cash flow and revenue", "Fiscal quarter (FYE May)", "Ratio (x)", height=410, y_tickformat=".1f")
    fig.update_xaxes(tickangle=-60, nticks=16)
    out.append(Chart("capex_intensity", 3, fig, "Capital intensity: capex relative to cash flow and revenue",
                     f"Above 1.0 the company spends more on capex than the business generates in operating cash (or in revenue), and must fund the gap with debt, equity or customer prepayments. "
                     f"Capex/OCF first exceeded 1.0 in {qq['label'][qq['capex_to_ocf_ttm'] > 1].iloc[0] if (qq['capex_to_ocf_ttm'] > 1).any() else 'never'} and is now {qq['capex_to_ocf_ttm'].iloc[-1]:.2f}x.", src, rng))

    # ================================================================ PAGE 4 : AI / RPO
    r = b.rpo
    rr = q[q["rpo"].notna()]
    rl = rr["label"].tolist()
    rrng = f"{rr['label'].iloc[0]} to {rr['label'].iloc[-1]}"
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, row_heights=[0.6, 0.4], vertical_spacing=0.07)
    fig.add_trace(go.Bar(x=rl, y=rr["rpo"] / 1e3, name="RPO (USD bn)", marker_color=T.BLUE), 1, 1)
    fig.add_trace(go.Scatter(x=rl, y=rr["rpo_to_ttm_revenue"], name="RPO / TTM revenue (x)", line=dict(color=T.ORANGE, width=2.4)), 2, 1)
    T.style(fig, "Remaining performance obligations (contracted backlog)", None, None, height=470, hover="x")
    fig.update_yaxes(title_text="RPO (USD bn)", row=1, col=1)
    fig.update_yaxes(title_text="Years of TTM revenue (x)", row=2, col=1)
    fig.update_xaxes(title_text="Fiscal quarter (FYE May)", tickangle=-60, row=2, col=1)
    out.append(Chart("rpo", 4, fig, "Remaining performance obligations (contracted backlog)",
                     f"RPO is revenue under signed contracts not yet recognised. It is ${rr['rpo'].iloc[-1]/1e3:,.0f}bn, {rr['rpo_to_ttm_revenue'].iloc[-1]:.1f}x trailing revenue (median since {rr['label'].iloc[0]}: "
                     f"{rr['rpo_to_ttm_revenue'].median():.1f}x). The biggest single-quarter step was {rr['label'][rr['rpo'].diff().idxmax()]} (+${rr['rpo'].diff().max()/1e3:,.0f}bn). "
                     "Backlog is a promise, not cash: it converts only as capacity is built and delivered, and only if counterparties perform.", b.sources["fundamentals"], rrng))

    cl = q[q["oci_revenue"].notna()]
    cll = cl["label"].tolist()
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, row_heights=[0.62, 0.38], vertical_spacing=0.07)
    other = (cl["revenue"] - cl["cloud_revenue"]) / 1e3
    fig.add_trace(go.Bar(x=cll, y=cl["oci_revenue"] / 1e3, name="Cloud infrastructure (OCI / IaaS)", marker_color=T.BLUE), 1, 1)
    fig.add_trace(go.Bar(x=cll, y=cl["saas_revenue"] / 1e3, name="Cloud applications (SaaS)", marker_color=T.AQUA), 1, 1)
    fig.add_trace(go.Bar(x=cll, y=other, name="Non-cloud (licence, hardware, services)", marker_color=T.AXIS), 1, 1)
    fig.add_trace(go.Scatter(x=cll, y=cl["oci_growth"], name="OCI growth YoY", line=dict(color=T.ORANGE, width=2.4)), 2, 1)
    fig.add_trace(go.Scatter(x=cll, y=cl["saas_growth"], name="SaaS growth YoY", line=dict(color=T.GREEN, width=2)), 2, 1)
    fig.update_layout(barmode="stack")
    T.style(fig, "Revenue mix and cloud-infrastructure growth", None, None, height=520, hover="x")
    fig.update_yaxes(title_text="Revenue (USD bn)", row=1, col=1)
    fig.update_yaxes(title_text="YoY growth", tickformat=".0%", row=2, col=1)
    fig.update_xaxes(title_text="Fiscal quarter (FYE May)", tickangle=-60, row=2, col=1)
    out.append(Chart("cloud_mix", 4, fig, "Revenue mix and cloud-infrastructure growth",
                     f"Quarterly revenue split into OCI (IaaS), SaaS and everything else, with growth rates below. OCI is ${cl['oci_revenue'].iloc[-1]/1e3:,.1f}bn a quarter "
                     f"({cl['oci_share_of_revenue'].iloc[-1]:.0%} of revenue, growing {cl['oci_growth'].iloc[-1]:.0%}) vs ${cl['oci_revenue'].iloc[0]/1e3:,.1f}bn in {cl['label'].iloc[0]}; SaaS grows "
                     f"{cl['saas_growth'].iloc[-1]:.0%}. OCI/SaaS come from Oracle's earnings-release tables (rounded to $0.1bn before FY26).",
                     b.sources["fundamentals"], f"{cl['label'].iloc[0]} to {cl['label'].iloc[-1]}"))

    # growth chain heatmap
    sc = r.scorecard.copy()
    z = sc.apply(pd.to_numeric, errors="coerce")
    shown = z.clip(-0.5, 1.5)
    txt = z.copy().astype(object)
    for i in z.index:
        for j in z.columns:
            v = z.loc[i, j]
            txt.loc[i, j] = "" if pd.isna(v) else (f"{v:.1f}x" if "Capex / OCF" in i else f"{v:.0%}")
    fig = go.Figure(go.Heatmap(z=shown.values, x=list(sc.columns), y=list(sc.index), text=txt.values, texttemplate="%{text}", colorscale=T.SEQ_BLUES, zmin=-0.5, zmax=1.5,
                               hovertemplate="%{y} - %{x}: %{text}<extra></extra>", showscale=False))
    T.style(fig, "The conversion chain: does growth at the top reach the bottom? (last six quarters)", None, None, height=470, legend=False, hover="closest")
    fig.update_yaxes(autorange="reversed", gridcolor="rgba(0,0,0,0)")
    out.append(Chart("growth_chain", 4, fig, "The conversion chain: does growth at the top reach the bottom?",
                     "Rows run from backlog (RPO) through cloud/OCI and revenue to operating income, operating cash flow and EPS, plus FCF margin and capex/OCF. Darker = higher; values are YoY growth unless "
                     "labelled. Read top to bottom: if growth fades down the chain (dark at the top, light at the bottom), the backlog is not yet turning into profit and cash; compare the FCF-margin and capex/OCF rows.",
                     src, rrng))

    # lead-lag
    ll = r.lead_lag.dropna(subset=["corr"])
    fig = go.Figure(go.Bar(x=[f"{k}Q" for k in ll.index], y=ll["corr"], marker_color=T.BLUE, name="Rank correlation",
                           error_y=dict(type="data", symmetric=False, array=(ll["ci_high"] - ll["corr"]).clip(lower=0), arrayminus=(ll["corr"] - ll["ci_low"]).clip(lower=0), color=T.INK2)))
    fig.add_hline(y=0, line=dict(color=T.AXIS, width=1))
    T.style(fig, "Lead-lag: RPO growth (t-k) vs revenue growth (t), Spearman correlation with 95% CI", "Lag k (quarters RPO growth leads revenue growth)", "Rank correlation", height=410, legend=False, hover="x")
    out.append(Chart("lead_lag", 4, fig, "Lead-lag: RPO growth (t-k) vs revenue growth (t)",
                     "Bars show the rank correlation between RPO growth k quarters ago and revenue growth today; whiskers are 95% intervals using an effective sample size that discounts autocorrelation. "
                     f"Peak rank-correlation {ll['corr'].max():.2f} at lag {int(ll['corr'].idxmax())}Q; the 95% interval at that lag runs {ll.loc[ll['corr'].idxmax(), 'ci_low']:.2f} to {ll.loc[ll['corr'].idxmax(), 'ci_high']:.2f} "
                     f"({'excludes' if ll.loc[ll['corr'].idxmax(), 'ci_low'] > 0 else 'includes'} zero; effective n = {ll.loc[ll['corr'].idxmax(), 'n_eff']:.0f}). With few quarters and one structural break the lag cannot be pinned down statistically.",
                     b.sources["fundamentals"], rrng))

    # conversion funnel
    last = q.iloc[-1]
    steps = ["Contracted backlog (RPO)", "Revenue (TTM)", "Operating income (TTM)", "Operating cash flow (TTM)", "Capex (TTM)", "Free cash flow (TTM)"]
    vals = [last["rpo"], last["revenue_ttm"], last["operating_income_ttm"], last["ocf_ttm"], -last["capex_ttm"], last["fcf_ttm"]]
    cols = [T.BLUE, T.BLUE, T.AQUA, T.AQUA, T.ORANGE, T.RED if last["fcf_ttm"] < 0 else T.GREEN]
    fig = go.Figure(go.Bar(x=[v / 1e3 for v in vals], y=steps, orientation="h", marker_color=cols,
                           text=[f"${v/1e3:,.1f}bn" for v in vals], textposition="outside"))
    T.style(fig, "RPO -> Revenue -> Cash flow: where the dollars end up (trailing twelve months)", "USD bn (backlog is a stock; the rest are 12-month flows)", None, height=400, legend=False, hover="y")
    fig.update_yaxes(autorange="reversed", gridcolor="rgba(0,0,0,0)")
    out.append(Chart("funnel", 4, fig, "RPO -> Revenue -> Cash flow: where the dollars end up",
                     f"Backlog dwarfs everything because it is a multi-year stock, not a 12-month flow. The flows tell the story: TTM operating cash flow ${last['ocf_ttm']/1e3:,.1f}bn against TTM capex "
                     f"${last['capex_ttm']/1e3:,.1f}bn leaves free cash flow of ${last['fcf_ttm']/1e3:,.1f}bn.", src, f"TTM to {last['label']} (quarter ended {q.index[-1].date()})"))

    # capital efficiency
    c2 = q[q["oci_revenue"].notna()]
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=c2["label"], y=c2["oci_revenue"] * 4 / 1e3, name="OCI revenue, annualised run-rate", line=dict(color=T.BLUE, width=2.6)))
    fig.add_trace(go.Scatter(x=c2["label"], y=c2["capex_ttm"] / 1e3, name="Capex (TTM)", line=dict(color=T.ORANGE, width=2.6)))
    fig.add_trace(go.Scatter(x=c2["label"], y=c2["ppe_net"] / 1e3, name="Net PP&E (period end)", line=dict(color=T.VIOLET, width=2.2, dash="dot")))
    T.style(fig, "Capital efficiency: OCI revenue run-rate vs capital deployed", "Fiscal quarter (FYE May)", "USD bn", height=430, hover="x")
    fig.update_xaxes(tickangle=-60)
    out.append(Chart("capital_efficiency", 4, fig, "Capital efficiency: OCI revenue run-rate vs capital deployed",
                     f"OCI revenue (annualised) against trailing capex and the net property base. Over the window OCI run-rate grew {c2['oci_revenue'].iloc[-1]/c2['oci_revenue'].iloc[0]:.1f}x while net PP&E grew "
                     f"{c2['ppe_net'].iloc[-1]/c2['ppe_net'].iloc[0]:.1f}x - partly timing (data centres are built ahead of revenue) and partly a question of eventual asset turnover, "
                     "which the valuation tests against hyperscaler peers.", src,
                     f"{c2['label'].iloc[0]} to {c2['label'].iloc[-1]}"))
    return out
